### ISSUE TITLE
Handling key release after lost window focus

### ISSUE THREAD

**Issue by fredriksa** [VesCodes/ImGui#13]
Hello,

I'm facing an issue where the ImGuiMod_Ctrl/Shift/Alt/Super keys are still considered to be down by the application after alt + shift tabbing out of the game window. This results in any call to ImGui::IsKeyDown(ImGuiKey_LeftAlt) == true before tabbing back or focusing the game window again. How would I best go about detecting focus loss and setting these keys to no longer being considered down? Or do you have any other ideas for how I should go about this?

And also, a big thank YOU for developing this excellent plugin🎉

**Comment by VesCodes** [comment]
Heya, this should be fixed with https://github.com/VesCodes/ImGui/commit/c41e0086db2865164ff60675bdeba4e78ae7d547

**Comment by fredriksa** [comment]
@VesCodes thanks a lot, this fixed it for me👍
