### ISSUE TITLE
Window does not resize when dragged to a new monitor with a different resolution 

### ISSUE THREAD

**Issue by jamesrawpower** [VesCodes/ImGui#17]
It seems that when you drag a window to a new monitor with a different resolution the window does not resize appropriately resulting in a clipped imgui draw result. This persists until you manually resize the window by dragging out from the corners or double clicking on the title bar to collapse it

**Comment by jamesrawpower** [comment]
I think it is something to do with the change in dpi scale. It looks as though the draw commands are not appropriately scaled until a resize window call is performed. When going from high to low dpi the window size stays the same, but the content gets clipped, when going from low to high dpi the content is drawn in a smaller area with black borders within the window. The window size stays the same throughout

**Comment by jamesrawpower** [comment]
I've made a pull request that fixes this

**Comment by VesCodes** [comment]
Merged PR https://github.com/VesCodes/ImGui/commit/67b82c1812b70e9a53f7f2142a49c8cee6d33c2c
