### ISSUE TITLE
Imgui MainViewport position in UnrealEditor builds is set in window (0;0) not in PIE viewport pos

### ISSUE THREAD

**Issue by RedwanFox** [VesCodes/ImGui#21]
Subj. I'm trying to setup debug imgui window in PIE

Way to reproduce:
1. Set up editor layout like so there is a tools column on the left and PIE viewport on the right
2. Add imgui window in PIE with set coordinates. it will appear outside of PIE viewport. See attached screenshot with details

Game Viewport and imgui main viewport have the same size. Also, I'm using 21:9 monitor if this relevant.

Code used for window creation
```cpp
void ATestGameState::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);
#if WITH_IMGUI
	ImGui::FScopedContext Context(this);
	if (Context)
	{
		FVector2D ViewportSize;
		GetWorld()->GetGameViewport()->GetViewportSize(ViewportSize);
		auto ImGuiViewportSize = ImGui::GetMainViewport()->Size;

		ImGui::SetNextWindowPos(FVector2f(20, 20));
		ImGui::SetNextWindowSize(FVector2f(500, 200), ImGuiCond_Appearing);
		if (ImGui::Begin("GameState", nullptr))
		{
                        // window contents
			ImGui::End();
		} else
		{
			ImGui::End();
		}
	}
#endif
}
```

![2024-09-25_17-45-42](https://github.com/user-attachments/assets/71413368-0394-462d-a0a7-538400565e69)

**Comment by VesCodes** [comment]
When setting window position you should base it off `ImGui::GetMainViewport()->Pos` like so:
```cpp
ImGui::SetNextWindowPos(FVector2f(ImGui::GetMainViewport()->Pos) + FVector2f(20, 20));
```

See this comment in the ImGui multi-viewport documentation:
https://github.com/ocornut/imgui/blob/793773209bb0fdeb8ccb756052e770457193c9f2/imgui.h#L3666
