### ISSUE TITLE
Left mouse button clicks and being held down in the Dear ImGui window disrupt keyboard input in the game view

### ISSUE THREAD

**Issue by nxrighthere** [VesCodes/ImGui#23]
I'm trying to make keyboard input work continuously for a player pawn, regardless of mouse input in the Dear ImGui window. The pawn's movement axes are bound using `UInputComponent`, which adds a world offset to the actor. The `ImGuiConfigFlags_NavNoCaptureKeyboard` configuration flag is enabled. For testing, I also tried using `ImGuiConfigFlags_NoKeyboard`, but it had no effect. Passing `ImGuiWindowFlags_NoNav` to the window, which is supposed to disable keyboard navigation and focus, also had no effect.

When holding the left mouse button in the ImGui window, keyboard input for the pawn is blocked. Additionally, moving the pawn and quickly clicking on the ImGui window sometimes results in the game view not receiving the key release event, causing the pawn to continue moving in the last active direction.

```
ImGuiIO& ImGuiIO = ImGui::GetIO();

ImGuiIO.ConfigFlags |= ImGuiConfigFlags_NavNoCaptureKeyboard;

ImGui::Begin("Test Window", nullptr, ImGuiWindowFlags_NoNav);
ImGui::End();
```

The only case where I want keyboard input in Dear ImGui is for text input fields. Any help would be greatly appreciated. Maybe @ocornut could offer some advice? 🙏🏻

**Comment by ocornut** [comment]
Activating any widget or performing any imgui interaction can potentially means the widget code may want to use keyboard inputs, so `io.WantCaptureKeyboard` has to be set regardless of navigation settings. Presumably your code or the integration is preventing underlying game to access keyboard when this is set, which is generally the desirable behavior.

I believe in this instance the backend or user code may want to ignore `io.WantCaptureKeyboard`, and instead only use `io.WantTextInput` as a way to filter how inputs are pipped to underlying application. I don't know where this check is performed but it may be an option in the integration/backend. However it means you are giving up using keyboard features in dear imgui other than text inputs.

You may manually override it on your end by using, preferably before `NewFrame()`:
```cpp
ImGui::SetNextFrameWantCaptureKeyboard(io.WantTextInput ? true : false);
ImGui::NewFrame(...);
```

(For consistency and completeness, I believe I should never set `io.WantCaptureKeyboard` when `ImGuiConfigFlags_NoKeyboard` is set, but that will not change anything to your issue.)

**Comment by nxrighthere** [comment]
Thank you for the detailed explanation, Omar! I have a better understanding of how keyboard input is handled now.

Playing around with `ImGui::SetNextFrameWantCaptureKeyboard()` resolved the issue.

Cheers! 🤝

**Comment by ocornut** [comment]
> (For consistency and completeness, I believe I should never set io.WantCaptureKeyboard when ImGuiConfigFlags_NoKeyboard is set, but that will not change anything to your issue.)

Pushed that change with https://github.com/ocornut/imgui/commit/c4bc6744824de148c3f825ffdcde785510e208ac
