### ISSUE TITLE
Always crash when play in pie

### ISSUE THREAD

**Issue by yolohz** [VesCodes/ImGui#25]
void AFateGameMode::Tick(float DeltaSeconds)
    {
	    Super::Tick(DeltaSeconds);
	    const ImGui::FScopedContext ScopedContext;
	    
	    if (ScopedContext.IsValid())
	    {
		    // Your ImGui code goes here!
		    ImGui::ShowDemoWindow();
	    }
    }

Ensure condition failed: g.WithinFrameScope [File:C:\Unreal Projects\Fate\Plugins\ImGui\Source\ThirdParty\ImGuiLibrary\imgui.cpp] [Line: 7062] 

any idea why this happen?

**Comment by VesCodes** [comment]
Replace
```
if (ScopedContext.IsValid())
```
with
```
if (ScopedContext)
```

**Comment by yolohz** [comment]
thanks, it work
