### ISSUE TITLE
How to render images?

### ISSUE THREAD

**Issue by Wyverex42** [VesCodes/ImGui#3]
Hi,

thanks for this library, it works so much better than another library we were using beforehand!

I'm currently trying to render an image with ImGui. I found one example within the plugin itself where the font atlas is built and then the pointer to the `UTexture2D` is passed as an `ImTextureID`. 

So I tried just passing a pointer to a `UTexture2D` (which is set as a default property on another class) to `ImGui::Image` but nothing is rendered. I also couldn't find where the conversion between `ImTextureID` and the actual draw commands is taking place so I can't say why it's not working.

Should this be supported?

**Comment by Wyverex42** [comment]
Ah nvm, it works with other textures! There's something wrong with the particular texture I'm trying to use

**Comment by VesCodes** [comment]
Heya!

You should be able to just pass a UTexture2D pointer to `ImGui::Image`, for example:
```cpp
ImGui::Image(GEngine->DefaultTexture, FVector2f(512, 512));
```
![image](https://github.com/VesCodes/ImGui/assets/1884844/25560669-5114-44c9-bf4a-7490cddd56e6)
